import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.substitutions import LaunchConfiguration
from launch.actions import DeclareLaunchArgument
from launch_ros.actions import Node
import xacro
import re


def generate_launch_description():
    use_sim_time = LaunchConfiguration('use_sim_time')

    # Process the URDF file
    pkg_share = get_package_share_directory('my_robot_description')
    description_dir = os.path.join(pkg_share, 'models', 'my_robot_description')
    xacro_file = os.path.join(description_dir, 'my_robot.urdf.xacro')
    controller_yaml = os.path.join(pkg_share, "config", "controller_config.yaml")

    # Force includes to resolve relative to description_dir
    cwd = os.getcwd()
    os.chdir(description_dir)
    try:
        doc = xacro.process_file(xacro_file, mappings={"controller_yaml": controller_yaml})
    finally:
        os.chdir(cwd)
    
    robot_xml = doc.toxml()

    # Remove XML declaration like <?xml version="1.0"?>
    robot_xml = re.sub(r"<\?xml[^>]*\?>", "", robot_xml).strip()

    # Remove XML comments <!-- ... --> (xacro adds a big autogenerated header)
    robot_xml = re.sub(r"<!--.*?-->", "", robot_xml, flags=re.DOTALL)

    # Optional: collapse whitespace (keeps XML valid, makes it less weird for parsers)
    robot_xml = re.sub(r"\s+", " ", robot_xml).strip()

    params = {'robot_description': robot_xml, 'use_sim_time': use_sim_time}


    node_robot_state_publisher = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        namespace='follower_robot',
        output='screen',
        parameters=[params],
    )

    return LaunchDescription([
        DeclareLaunchArgument(
            'use_sim_time',
            default_value='false',
            description='Use sim time if true'
        ),
        node_robot_state_publisher,
    ])
